name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright/Percy tests
      run: pnpm exec percy exec -- pnpm exec playwright test --grep "@percy"
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        DEMO_URL: ${{ secrets.DEMO_URL }}
        PERCY_PAGE_LOAD_TIMEOUT: 60000
        CORRECT_USER: ${{ secrets.CORRECT_USER }}
        CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
